services:
  _defaults:
    autoconfigure: true
    autowire: true

  JoseUgal\Apps\Mooc\Backend\Controller\:
    resource: '../src/Controller'
    tags: ['controller.service_arguments']

  # Wire
  JoseUgal\Shared\:
    resource: '../../../../src/Shared'

  JoseUgal\Mooc\:
    resource: '../../../../src/Mooc'

  # -- TAGGING --
  JoseUgal\Shared\Infrastructure\Symfony\AddJsonBodyToRequestListener:
    tags:
      - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }